### ISSUE TITLE
Feedback 21 okt

### ISSUE THREAD

**Issue by Anna-Kyra** [KaanKalmi/i-love-web#8]
Top:
- De intro animatie is echt heel nice!! + goede muziek erachter.
- Yey!!! Je hebt GSAP gebruikt!

Tip: 
### HTML
https://github.com/KaanKalmi/i-love-web/blob/54df29f64c32247342e5df1e2aa25ad85359a785/src/app.html#L2
Je taal staat nog in engels. Ik gok dat je hem in het Nederlands maakt deze website, omdat je plaathouder tekst ook Nederlands is.

https://github.com/KaanKalmi/i-love-web/blob/54df29f64c32247342e5df1e2aa25ad85359a785/src/lib/components/Intro.svelte#L59-L65

`<span>` is eigenlijk het zelfde als een `<div>` alleen binnen een tag. Kan dit ook niet een `<p>` tag worden om het semantischer te maken? 
Wacht kan die .marque container niet gewoon een list zijn?

### CSS

```CSS
*,
*::before,
*::after {
margin: 0;
padding: 0;
box-sizing: border-box;
}
```
- Misschien handig om dit nog toe te voegen boven in je globals.css document. Dan kan je met een schonen lei. Waarschijnlijk maakt dit je code wel kapot, omdat je al wat stijging hebt gedaan. Maar die box-sizing is wel handig voor hoe je padding werkt.

**Comment by KaanKalmi** [comment]
### HTML
Dat staat voorlopig in nederlands ja, ik ga mn portfolio in het engels maken tho
